version = 1

exclude_patterns = ["/js/**"]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "nodejs",
    "jquery"
  ]

# Suppress explicit-any errors
[[transformations]]
ignore_patterns = ["**"]

  [transformations.suppress]
  issues = ["explicit-any", "JS-0240", "JS-C1002"]