import {
  POINT,
  LINE,
  BOX,
  SOLIDBOX,
  SCALEDSOLIDBOX,
  SCALEDSOLIDTOWER,
  ASSOC,
  SHAPE,
  TEXT,
  STACKEDTOWER,
} from "./config";
import {
  makeCaloClusters,
  makeCaloTower,
  makeCSC,
  makeCSCDigis_V2,
  makeCSCLCTCorrelatedLCTDigis,
  makeCSCLCTDigis,
  makeCSCRecHit2Ds_V2,
  makeCSCRecHit2DsRZ,
  makeCSCSegments,
  makeCSCSegmentsRZ,
  makeCSCStripDigis,
  makeCSCWireDigis,
  makeDT,
  makeDTRecHits,
  makeDTRecHitsRZ,
  makeDTRecSegments,
  makeDTRecSegmentsRZ,
  makeEcal,
  makeEcalDigi,
  makeEcalPFCandidateTowers,
  makeEcalPFCandidateTowersRZ,
  makeERecHit_RZ,
  makeERecHit_V2,
  makeEvent,
  makeGEM,
  makeGEMDigis_V2,
  makeGEMRecHits_V2,
  makeGEMRecHitsRZ,
  makeGEMSegments_V2,
  makeHcal,
  makeHcalPFCandidateTowers,
  makeHcalPFCandidateTowersRZ,
  makeHGCRecHit,
  makeHRecHit_RZ,
  makeHRecHit_V2,
  makeJet,
  makeJetRZ,
  makeJetWithVertex,
  makeJetWithVertexRZ,
  makeMET,
  makeMuonChamber,
  makePhoton,
  makePhotonRZ,
  makeProtons,
  makeRPC,
  makeRPCRecHits,
  makeRPCRecHitsRZ,
  makeSimVertex,
  makeThickTracks,
  makeThickTracksRZ,
  makeTrackerPiece,
  makeTrackingClusters,
  makeTrackingClustersRZ,
  makeTrackingRecHits,
  makeTrackingRecHitsRZ,
  makeTrackPoints,
  makeTrackPointsRZ,
  makeTracks,
  makeTracksRZ,
  makeVertex,
  makeVertexCompositeCandidate,
} from "./objects-draw";
import { addControllers, addInfo } from "./tree-view";

// skipcq: JS-0323
const detector_description: Record<string, Record<string, any>> = {
  "3D": {
    RPCMinusEndcap3D_V1: {
      type: BOX,
      on: false,
      group: "Detector",
      name: "Resistive Plate Chambers (-)",
      fn: makeRPC,
      style: { color: "rgb(60%, 80%, 0%)", opacity: 0.2, linewidth: 1.0 },
    },
    RPCPlusEndcap3D_V1: {
      type: BOX,
      on: false,
      group: "Detector",
      name: "Resistive Plate Chambers (+)",
      fn: makeRPC,
      style: { color: "rgb(60%, 80%, 0%)", opacity: 0.2, linewidth: 1.0 },
    },
    RPCBarrel3D_V1: {
      type: BOX,
      on: false,
      group: "Detector",
      name: "Resistive Plate Chambers (barrel)",
      fn: makeRPC,
      style: { color: "rgb(60%, 80%, 0%)", opacity: 0.2, linewidth: 1.0 },
    },
    GEMMinus3D_V1: {
      type: BOX,
      on: false,
      group: "Detector",
      name: "Gas Electron Multipliers (-)",
      fn: makeGEM,
      style: { color: "rgb(30%, 70%, 10%)", opacity: 0.5, linewidth: 1.0 },
    },
    GEMPlus3D_V1: {
      type: BOX,
      on: false,
      group: "Detector",
      name: "Gas Electron Multipliers (+)",
      fn: makeGEM,
      style: { color: "rgb(30%, 70%, 10%)", opacity: 0.5, linewidth: 1.0 },
    },
    CSCMinus3D_V1: {
      type: BOX,
      on: false,
      group: "Detector",
      name: "Cathode Strip Chambers",
      fn: makeCSC,
      style: { color: "rgb(60%, 70%, 10%)", opacity: 0.2, linewidth: 1.0 },
    },
    CSCPlus3D_V1: {
      type: BOX,
      on: false,
      group: "Detector",
      name: "Cathode Strip Chambers",
      fn: makeCSC,
      style: { color: "rgb(60%, 70%, 10%)", opacity: 0.2, linewidth: 1.0 },
    },
    DTs3D_V1: {
      type: BOX,
      on: false,
      group: "Detector",
      name: "Drift Tubes",
      fn: makeDT,
      style: { color: "rgb(80%, 40%, 0%)", opacity: 0.2, linewidth: 1.0 },
    },
    HcalForwardMinus3D_V1: {
      type: BOX,
      on: false,
      group: "Detector",
      name: "HCAL Forward (-)",
      fn: makeHcal,
      style: { color: "rgb(70%, 70%, 0%)", opacity: 0.1, linewidth: 1.0 },
    },
    HcalForwardPlus3D_V1: {
      type: BOX,
      on: false,
      group: "Detector",
      name: "HCAL Forward (+)",
      fn: makeHcal,
      style: { color: "rgb(70%, 70%, 0%)", opacity: 0.1, linewidth: 1.0 },
    },
    HcalOuter3D_V1: {
      type: BOX,
      on: false,
      group: "Detector",
      name: "HCAL Outer",
      fn: makeHcal,
      style: { color: "rgb(70%, 70%, 0%)", opacity: 0.04, linewidth: 1.0 },
    },
    HcalEndcapMinus3D_V1: {
      type: BOX,
      on: false,
      group: "Detector",
      name: "HCAL Endcap (-)",
      fn: makeHcal,
      style: { color: "rgb(70%, 70%, 0%)", opacity: 0.01, linewidth: 1.0 },
    },
    HcalEndcapPlus3D_V1: {
      type: BOX,
      on: false,
      group: "Detector",
      name: "HCAL Endcap (+)",
      fn: makeHcal,
      style: { color: "rgb(70%, 70%, 0%)", opacity: 0.01, linewidth: 1.0 },
    },
    HcalBarrel3D_V1: {
      type: BOX,
      on: false,
      group: "Detector",
      name: "HCAL Barrel",
      fn: makeHcal,
      style: { color: "rgb(70%, 70%, 0%)", opacity: 0.01, linewidth: 1.0 },
    },
    EcalEndcapMinus3D_V1: {
      type: BOX,
      on: false,
      group: "Detector",
      name: "ECAL Endcap (-)",
      fn: makeEcal,
      style: { color: "rgb(50%, 80%, 100%)", opacity: 0.05, linewidth: 0.5 },
    },
    EcalEndcapPlus3D_V1: {
      type: BOX,
      on: false,
      group: "Detector",
      name: "ECAL Endcap (+)",
      fn: makeEcal,
      style: { color: "rgb(50%, 80%, 100%)", opacity: 0.05, linewidth: 0.5 },
    },
    EcalBarrel3D_V1: {
      type: BOX,
      on: true,
      group: "Detector",
      name: "ECAL Barrel",
      fn: makeEcal,
      style: { color: "rgb(50%, 80%, 100%)", opacity: 0.01, linewidth: 0.5 },
    },
    SiStripTECMinus3D_V1: {
      type: BOX,
      on: false,
      group: "Detector",
      name: "Tracker Endcap (-)",
      fn: makeTrackerPiece,
      style: { color: "rgb(100%, 100%, 0%)", opacity: 0.5, linewidth: 1.0 },
    },
    SiStripTECPlus3D_V1: {
      type: BOX,
      on: false,
      group: "Detector",
      name: "Tracker Endcap (+)",
      fn: makeTrackerPiece,
      style: { color: "rgb(100%, 100%, 0%)", opacity: 0.5, linewidth: 1.0 },
    },
    SiStripTIDMinus3D_V1: {
      type: BOX,
      on: false,
      group: "Detector",
      name: "Tracker Inner Detector (-)",
      fn: makeTrackerPiece,
      style: { color: "rgb(100%, 100%, 0%)", opacity: 0.5, linewidth: 1.0 },
    },
    SiStripTIDPlus3D_V1: {
      type: BOX,
      on: false,
      group: "Detector",
      name: "Tracker Inner Detector (+)",
      fn: makeTrackerPiece,
      style: { color: "rgb(100%, 100%, 0%)", opacity: 0.5, linewidth: 1.0 },
    },
    SiStripTOB3D_V1: {
      type: BOX,
      on: false,
      group: "Detector",
      name: "Tracker Outer Barrel",
      fn: makeTrackerPiece,
      style: { color: "rgb(100%, 100%, 0%)", opacity: 0.5, linewidth: 1.0 },
    },
    SiStripTIB3D_V1: {
      type: BOX,
      on: false,
      group: "Detector",
      name: "Tracker Inner Barrel",
      fn: makeTrackerPiece,
      style: { color: "rgb(100%, 100%, 0%)", opacity: 0.5, linewidth: 1.0 },
    },
    PixelEndcapMinus3D_V1: {
      type: BOX,
      on: false,
      group: "Detector",
      name: "Pixel Endcap (-)",
      fn: makeTrackerPiece,
      style: { color: "rgb(100%, 100%, 0%)", opacity: 0.5, linewidth: 1.0 },
    },
    PixelEndcapPlus3D_V1: {
      type: BOX,
      on: false,
      group: "Detector",
      name: "Pixel Endcap (+)",
      fn: makeTrackerPiece,
      style: { color: "rgb(100%, 100%, 0%)", opacity: 0.5, linewidth: 1.0 },
    },
    PixelBarrel3D_V1: {
      type: BOX,
      on: false,
      group: "Detector",
      name: "Pixel Barrel",
      fn: makeTrackerPiece,
      style: { color: "rgb(100%, 100%, 0%)", opacity: 0.5, linewidth: 1.0 },
    },
    PixelEndcapMinus3D_V2: {
      type: BOX,
      on: false,
      group: "Detector",
      name: "Pixel Endcap (-)",
      fn: makeTrackerPiece,
      style: { color: "rgb(100%, 100%, 0%)", opacity: 0.5, linewidth: 1.0 },
    },
    PixelEndcapPlus3D_V2: {
      type: BOX,
      on: false,
      group: "Detector",
      name: "Pixel Endcap (+)",
      fn: makeTrackerPiece,
      style: { color: "rgb(100%, 100%, 0%)", opacity: 0.5, linewidth: 1.0 },
    },
    PixelBarrel3D_V2: {
      type: BOX,
      on: false,
      group: "Detector",
      name: "Pixel Barrel",
      fn: makeTrackerPiece,
      style: { color: "rgb(100%, 100%, 0%)", opacity: 0.5, linewidth: 1.0 },
    },
  },

  RPhi: {
    DTsRPhi_V1: {
      type: BOX,
      on: true,
      group: "Detector",
      name: "Drift Tubes RPhi",
      fn: makeDT,
      style: { color: "rgb(80%, 40%, 0%)", opacity: 0.5, linewidth: 1.0 },
    },
    HcalOuterRPhi_V1: {
      type: BOX,
      on: true,
      group: "Detector",
      name: "HCAL Outer RPhi",
      fn: makeHcal,
      style: { color: "rgb(70%, 70%, 0%)", opacity: 0.5, linewidth: 1.0 },
    },
    HcalBarrelRPhi_V1: {
      type: BOX,
      on: true,
      group: "Detector",
      name: "HCAL Barrel RPhi",
      fn: makeHcal,
      style: { color: "rgb(70%, 70%, 0%)", opacity: 0.5, linewidth: 1.0 },
    },
    EcalBarrelRPhi_V1: {
      type: BOX,
      on: true,
      group: "Detector",
      name: "ECAL Barrel RPhi",
      fn: makeEcal,
      style: { color: "rgb(50%, 80%, 100%)", opacity: 0.75, linewidth: 1.0 },
    },
    TrackerRPhi_V1: {
      type: BOX,
      on: true,
      group: "Detector",
      name: "Tracker RPhi",
      fn: makeTrackerPiece,
      style: { color: "rgb(100%, 100%, 0%)", opacity: 0.5, linewidth: 1.0 },
    },
  },

  RhoZ: {
    GEMRZ_V1: {
      type: BOX,
      on: true,
      group: "Detector",
      name: "Gas Electron Multipliers RZ",
      fn: makeGEM,
      style: { color: "rgb(30%, 70%, 10%)", opacity: 0.5, linewidth: 1.0 },
    },
    CSCRZ_V1: {
      type: BOX,
      on: true,
      group: "Detector",
      name: "Cathode Strip Chambers RZ",
      fn: makeCSC,
      style: { color: "rgb(60%, 70%, 10%)", opacity: 0.5, linewidth: 1.0 },
    },
    DTsRZ_V1: {
      type: BOX,
      on: true,
      group: "Detector",
      name: "Drift Tubes RZ",
      fn: makeDT,
      style: { color: "rgb(80%, 40%, 0%)", opacity: 0.5, linewidth: 1.0 },
    },
    HcalForwardRZ_V1: {
      type: BOX,
      on: true,
      group: "Detector",
      name: "HCAL Forward RZ",
      fn: makeHcal,
      style: { color: "rgb(70%, 70%, 0%)", opacity: 0.5, linewidth: 1.0 },
    },
    HcalOuterRZ_V1: {
      type: BOX,
      on: true,
      group: "Detector",
      name: "HCAL Outer RZ",
      fn: makeHcal,
      style: { color: "rgb(70%, 70%, 0%)", opacity: 0.5, linewidth: 1.0 },
    },
    HcalEndcapRZ_V1: {
      type: BOX,
      on: true,
      group: "Detector",
      name: "HCAL Endcap RZ",
      fn: makeHcal,
      style: { color: "rgb(70%, 70%, 0%)", opacity: 0.5, linewidth: 1.0 },
    },
    HcalBarrelRZ_V1: {
      type: BOX,
      on: true,
      group: "Detector",
      name: "HCAL Barrel RZ",
      fn: makeHcal,
      style: { color: "rgb(70%, 70%, 0%)", opacity: 0.5, linewidth: 1.0 },
    },
    EcalEndcapRZ_V1: {
      type: BOX,
      on: true,
      group: "Detector",
      name: "ECAL Endcap RZ",
      fn: makeEcal,
      style: { color: "rgb(50%, 80%, 100%)", opacity: 0.75, linewidth: 1.0 },
    },
    EcalBarrelRZ_V1: {
      type: BOX,
      on: true,
      group: "Detector",
      name: "ECAL Barrel RZ",
      fn: makeEcal,
      style: { color: "rgb(50%, 80%, 100%)", opacity: 0.75, linewidth: 1.0 },
    },
    TrackerRZ_V1: {
      type: BOX,
      on: true,
      group: "Detector",
      name: "Tracker RZ",
      fn: makeTrackerPiece,
      style: { color: "rgb(100%, 100%, 0%)", opacity: 0.5, linewidth: 1.0 },
    },
  },
};

// skipcq: JS-0323
const event_description: Record<string, Record<string, any>> = {
  "3D": {
    SuperClusters_V1: {
      type: ASSOC,
      on: false,
      group: "ECAL",
      name: "SuperClusters",
      extra: "RecHitFractions_V1",
      assoc: "SuperClusterRecHitFractions_V1",
      fn: makeCaloClusters,
      style: { color: "rgb(100%, 20%, 0%)", opacity: 1.0 },
    },
    EEDigis_V1: {
      type: SCALEDSOLIDTOWER,
      on: false,
      group: "ECAL",
      name: "Endcap Digis",
      fn: makeEcalDigi,
      style: { color: "rgb(100%, 20%, 0%)", opacity: 0.5, linewidth: 0.5 },
      scale: 1.0,
      selection: { min_energy: 0.5 },
    },
    EBDigis_V1: {
      type: SCALEDSOLIDTOWER,
      on: false,
      group: "ECAL",
      name: "Barrel Digis",
      fn: makeEcalDigi,
      style: { color: "rgb(100%, 20%, 0%)", opacity: 0.5, linewidth: 0.5 },
      scale: 1.0,
      selection: { min_energy: 0.25 },
    },
    EERecHits_V2: {
      type: SCALEDSOLIDTOWER,
      on: true,
      group: "ECAL",
      name: "Endcap Rec. Hits",
      fn: makeERecHit_V2,
      style: { color: "rgb(10%, 100%, 10%)", opacity: 0.5, linewidth: 0.5 },
      scale: 0.01,
      selection: { min_energy: 0.5 },
    },
    ESRecHits_V2: {
      type: SCALEDSOLIDTOWER,
      on: false,
      group: "ECAL",
      name: "Preshower Rec. Hits",
      fn: makeERecHit_V2,
      style: { color: "rgb(100%, 60%, 0%)", opacity: 0.5, linewidth: 0.5 },
      scale: 100.0,
      selection: { min_energy: 0.0005 },
    },
    EBRecHits_V2: {
      type: SCALEDSOLIDTOWER,
      on: true,
      group: "ECAL",
      name: "Barrel Rec. Hits",
      fn: makeERecHit_V2,
      style: { color: "rgb(10%, 100%, 10%)", opacity: 0.5, linewidth: 0.5 },
      scale: 0.1,
      selection: { min_energy: 0.25 },
    },
    EcalTowers_V1: {
      type: SCALEDSOLIDTOWER,
      on: false,
      group: "ECAL",
      name: "EcalTowers",
      fn: makeEcalPFCandidateTowers,
      style: { color: "rgb(10%, 100%, 10%)", opacity: 0.5, scale: 0.1 },
      selection: { min_energy: 1.5 },
    },
    HcalTowers_V1: {
      type: SCALEDSOLIDTOWER,
      on: false,
      group: "HCAL",
      name: "HcalTowers",
      fn: makeHcalPFCandidateTowers,
      style: { color: "rgb(20%, 70%, 100%)", opacity: 0.5, scale: 0.1 },
      selection: { min_energy: 1.5 },
    },
    HGCEERecHits_V1: {
      type: SCALEDSOLIDBOX,
      on: true,
      group: "ECAL",
      name: "HGC EE Rec. Hits",
      fn: makeHGCRecHit,
      style: { color: "rgb(10%, 100%, 10%)", opacity: 0.5, linewidth: 0.25 },
      selection: { min_energy: 0.01 },
    },
    HFRecHits_V2: {
      type: SCALEDSOLIDBOX,
      on: false,
      group: "HCAL",
      name: "Forward Rec. Hits",
      fn: makeHRecHit_V2,
      style: { color: "rgb(60%, 100%, 100%)", opacity: 0.5, linewidth: 0.25 },
      selection: { min_energy: 0.0 },
    },
    HORecHits_V2: {
      type: SCALEDSOLIDBOX,
      on: false,
      group: "HCAL",
      name: "Outer Rec. Hits",
      fn: makeHRecHit_V2,
      style: { color: "rgb(20%, 70%, 100%)", opacity: 0.5, linewidth: 0.25 },
      selection: { min_energy: 1.0 },
    },
    HERecHits_V2: {
      type: SCALEDSOLIDBOX,
      on: true,
      group: "HCAL",
      name: "Endcap Rec. Hits",
      fn: makeHRecHit_V2,
      style: { color: "rgb(20%, 70%, 100%)", opacity: 0.5, linewidth: 0.25 },
      selection: { min_energy: 0.0 },
    },
    HBRecHits_V2: {
      type: SCALEDSOLIDBOX,
      on: true,
      group: "HCAL",
      name: "Barrel Rec. Hits",
      fn: makeHRecHit_V2,
      style: { color: "rgb(20%, 70%, 100%)", opacity: 0.5, linewidth: 0.25 },
      selection: { min_energy: 0.0 },
    },
    HGCHEBRecHits_V1: {
      type: SCALEDSOLIDBOX,
      on: true,
      group: "HCAL",
      name: "HGC HE Back Rec. Hits",
      fn: makeHGCRecHit,
      style: { color: "rgb(20%, 70%, 100%)", opacity: 0.5, linewidth: 0.25 },
      selection: { min_energy: 0.01 },
    },
    HGCHEFRecHits_V1: {
      type: SCALEDSOLIDBOX,
      on: true,
      group: "HCAL",
      name: "HGC HE Front Rec. Hits",
      fn: makeHGCRecHit,
      style: { color: "rgb(20%, 70%, 100%)", opacity: 0.5, linewidth: 0.25 },
      selection: { min_energy: 0.01 },
    },
    Tracks_V1: {
      type: ASSOC,
      on: true,
      group: "Tracking",
      name: "Tracks (reco.)",
      extra: "Extras_V1",
      assoc: "TrackExtras_V1",
      fn: makeTracks,
      style: {
        color: "rgb(100%, 100%, 0%)",
        opacity: 0.5,
        lineCaps: "square",
        linewidth: 1,
      },
      selection: { min_pt: 1.0, index: 2 },
    },
    Tracks_V2: {
      type: ASSOC,
      on: true,
      group: "Tracking",
      name: "Tracks (reco.)",
      extra: "Extras_V1",
      assoc: "TrackExtras_V1",
      fn: makeTracks,
      style: {
        color: "rgb(100%, 100%, 0%)",
        opacity: 0.5,
        lineCaps: "square",
        linewidth: 1,
      },
      selection: { min_pt: 1.0, index: 2 },
    },
    Tracks_V3: {
      type: ASSOC,
      on: true,
      group: "Tracking",
      name: "Tracks (reco.)",
      extra: "Extras_V1",
      assoc: "TrackExtras_V1",
      fn: makeTracks,
      style: {
        color: "rgb(100%, 100%, 0%)",
        opacity: 0.5,
        lineCaps: "square",
        linewidth: 1,
      },
      selection: { min_pt: 1.0, index: 2 },
    },
    Tracks_V4: {
      type: ASSOC,
      on: true,
      group: "Tracking",
      name: "Tracks (reco.)",
      extra: "Extras_V1",
      assoc: "TrackExtras_V1",
      fn: makeTracks,
      style: {
        color: "rgb(100%, 100%, 0%)",
        opacity: 0.5,
        lineCaps: "square",
        linewidth: 1,
      },
      selection: { min_pt: 1.0, index: 2 },
    },
    TrackDets_V1: {
      type: BOX,
      on: false,
      group: "Tracking",
      name: "Matching Tracker Dets",
      fn: makeTrackerPiece,
      style: { color: "rgb(100%, 100%, 0%)", opacity: 0.5, linewidth: 0.5 },
    },
    TrackingRecHits_V1: {
      type: POINT,
      on: false,
      group: "Tracking",
      name: "Tracking Rec Hits",
      fn: makeTrackingRecHits,
      style: { color: "rgb(100%, 100%, 0%)", size: 0.05 },
    },
    SiStripClusters_V1: {
      type: POINT,
      on: false,
      group: "Tracking",
      name: "Si Strip Clusters",
      fn: makeTrackingClusters,
      style: { color: "rgb(80%, 20%, 0%)", size: 0.05 },
    },
    SiPixelClusters_V1: {
      type: POINT,
      on: false,
      group: "Tracking",
      name: "Si Pixel Clusters",
      fn: makeTrackingClusters,
      style: { color: "rgb(100%, 40%, 0%)", size: 0.05 },
    },
    Event_V1: {
      type: TEXT,
      on: true,
      group: "Provenance",
      name: "Event",
      fn: makeEvent,
      style: {},
    },
    Event_V2: {
      type: TEXT,
      on: true,
      group: "Provenance",
      name: "Event",
      fn: makeEvent,
      style: {},
    },
    Event_V3: {
      type: TEXT,
      on: true,
      group: "Provenance",
      name: "Event",
      fn: makeEvent,
      style: {},
    },
    DTRecHits_V1: {
      type: SOLIDBOX,
      on: false,
      group: "Muon",
      name: "DT Rec. Hits",
      fn: makeDTRecHits,
      style: { color: "rgb(0%, 100%, 0%)", opacity: 0.5, linewidth: 1 },
    },
    DTRecSegment4D_V1: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "DT Rec. Segments (4D)",
      fn: makeDTRecSegments,
      style: { color: "rgb(100%, 100%, 0%)", opacity: 1.0, linewidth: 1.5 },
    },
    RPCRecHits_V1: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "RPC Rec. Hits",
      fn: makeRPCRecHits,
      style: { color: "rgb(80%, 100%, 0%)", opacity: 1.0, linewidth: 1.5 },
    },
    MatchingGEMs_V1: {
      type: SOLIDBOX,
      on: true,
      group: "Muon",
      name: "Matching GEMs",
      fn: makeMuonChamber,
      style: { color: "rgb(100%,0%,10%)", opacity: 0.1, linewidth: 1 },
    },
    GEMDigis_V2: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "GEM Strip Digis",
      fn: makeGEMDigis_V2,
      style: { color: "rgb(100%, 10%, 100%)", opacity: 0.8, linewidth: 1 },
    },
    GEMRecHits_V2: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "GEM Rec. Hits (2D)",
      fn: makeGEMRecHits_V2,
      style: { color: "rgb(60%, 100%, 70%)", opacity: 1.0, linewidth: 1 },
    },
    GEMSegments_V1: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "GEM Segments",
      fn: makeGEMSegments_V2,
      style: { color: "rgb(100%, 70%, 100%)", opacity: 1.0, linewidth: 1 },
    },
    GEMSegments_V2: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "GEM Segments",
      fn: makeGEMSegments_V2,
      style: { color: "rgb(100%, 70%, 100%)", opacity: 1.0, linewidth: 1 },
    },
    GEMSegments_V3: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "GEM Segments",
      fn: makeGEMSegments_V2,
      style: { color: "rgb(100%, 70%, 100%)", opacity: 1.0, linewidth: 1 },
    },
    CSCStripDigis_V1: {
      type: SOLIDBOX,
      on: false,
      group: "Muon",
      name: "CSC Strip Digis",
      fn: makeCSCStripDigis,
      style: { color: "rgb(100%, 20%, 100%)", opacity: 0.5, linewidth: 1 },
    },
    CSCWireDigis_V1: {
      type: SOLIDBOX,
      on: false,
      group: "Muon",
      name: "CSC Wire Digis",
      fn: makeCSCWireDigis,
      style: { color: "rgb(100%, 60%, 100%)", opacity: 0.5, linewidth: 1 },
    },
    CSCStripDigis_V2: {
      type: LINE,
      on: false,
      group: "Muon",
      name: "CSC Strip Digis",
      fn: makeCSCDigis_V2,
      style: { color: "rgb(100%, 20%, 100%)", opacity: 0.8, linewidth: 1 },
    },
    CSCWireDigis_V2: {
      type: LINE,
      on: false,
      group: "Muon",
      name: "CSC Wire Digis",
      fn: makeCSCDigis_V2,
      style: { color: "rgb(100%, 60%, 100%)", opacity: 0.5, linewidth: 1 },
    },
    CSCLCTDigis_V1: {
      type: POINT,
      on: false,
      group: "Muon",
      name: "CSC LCT Digis",
      fn: makeCSCLCTDigis,
      style: { color: "rgb(0%, 100%, 100%)", size: 0.15 },
    },
    CSCCorrelatedLCTDigis_V2: {
      type: LINE,
      on: false,
      group: "Muon",
      name: "CSC Correlated LCT Digis",
      fn: makeCSCLCTCorrelatedLCTDigis,
      style: { color: "rgb(0%,100%,100%)", opacity: 0.8, linewidth: 2 },
    },
    MatchingCSCs_V1: {
      type: SOLIDBOX,
      on: true,
      group: "Muon",
      name: "Matching CSCs",
      fn: makeMuonChamber,
      style: { color: "rgb(100%,0%,0%)", opacity: 0.1, linewidth: 1 },
    },
    CSCRecHit2Ds_V2: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "CSC Rec. Hits (2D)",
      fn: makeCSCRecHit2Ds_V2,
      style: { color: "rgb(60%, 100%, 90%)", opacity: 1.0, linewidth: 1 },
    },
    CSCSegments_V1: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "CSC Segments",
      fn: makeCSCSegments,
      style: { color: "rgb(100%, 60%, 100%)", opacity: 1.0, linewidth: 1.5 },
    },
    CSCSegments_V2: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "CSC Segments",
      fn: makeCSCSegments,
      style: { color: "rgb(100%, 60%, 100%)", opacity: 1.0, linewidth: 1.5 },
    },
    CSCSegments_V3: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "CSC Segments",
      fn: makeCSCSegments,
      style: { color: "rgb(100%, 60%, 100%)", opacity: 1.0, linewidth: 1.5 },
    },
    MuonChambers_V1: {
      type: SOLIDBOX,
      on: true,
      group: "Muon",
      name: "Matching muon chambers",
      fn: makeMuonChamber,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 0.1, linewidth: 1 },
    },
    CaloTowers_V2: {
      type: STACKEDTOWER,
      on: false,
      group: "Physics",
      name: "Calo Towers",
      fn: makeCaloTower,
      style: {
        ecolor: "rgb(100%, 0%, 0%)",
        hcolor: "rgb(0%, 0%, 100%)",
        opacity: 0.5,
        linewidth: 1.0,
      },
      scale: 0.1,
      selection: { min_energy: 0.1 },
    },
    CaloTowers_V3: {
      type: STACKEDTOWER,
      on: false,
      group: "Physics",
      name: "Calo Towers",
      fn: makeCaloTower,
      style: {
        ecolor: "rgb(100%, 0%, 0%)",
        hcolor: "rgb(0%, 0%, 100%)",
        opacity: 0.5,
        linewidth: 1.0,
      },
      scale: 0.1,
      selection: { min_energy: 1.0 },
    },
    METs_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "Missing Et (Reco)",
      fn: makeMET,
      style: { color: "rgb(100%, 50%, 100%)", linewidth: 2, scale: 0.025 },
      selection: { min_pt: 0.0 },
    },
    PFMETs_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "Missing Et (PF)",
      fn: makeMET,
      style: { color: "rgb(100%, 50%, 100%)", linewidth: 2, scale: 0.025 },
      selection: { min_pt: 0.0 },
    },
    PATMETs_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "Missing Et (PAT)",
      fn: makeMET,
      style: { color: "rgb(100%, 50%, 100%)", linewidth: 2, scale: 0.025 },
      selection: { min_pt: 0.0 },
    },
    Jets_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "Jets (Reco)",
      fn: makeJet,
      style: { color: "rgb(100%, 100%, 0%)", opacity: 0.75 },
      selection: { min_et: 10.0 },
    },
    PFJets_V1: {
      type: SHAPE,
      on: true,
      group: "Physics",
      name: "Jets (PF)",
      fn: makeJet,
      style: { color: "rgb(100%, 100%, 0%)", opacity: 0.6 },
      selection: { min_et: 10.0 },
      cuts: true,
    },
    PFJets_V2: {
      type: SHAPE,
      on: true,
      group: "Physics",
      name: "Jets (PF)",
      fn: makeJetWithVertex,
      style: { color: "rgb(100%, 100%, 0%)", opacity: 0.6 },
      selection: { min_et: 10.0 },
      cuts: true,
    },
    GenJets_V1: {
      type: SHAPE,
      on: true,
      group: "Physics",
      name: "Jets (Sim)",
      fn: makeJet,
      style: { color: "rgb(100%, 75%, 0%)", opacity: 0.8 },
      selection: { min_et: 10.0 },
    },
    PATJets_V1: {
      type: SHAPE,
      on: true,
      group: "Physics",
      name: "Jets (PAT)",
      fn: makeJet,
      style: { color: "rgb(100%, 50%, 0%)", opacity: 0.3 },
      selection: { min_et: 10.0 },
    },
    Photons_V1: {
      type: SHAPE,
      on: true,
      group: "Physics",
      name: "Photons (Reco)",
      fn: makePhoton,
      style: { color: "rgb(67%, 0%, 100%)", opacity: 1.0, linewidth: 2 },
      selection: { min_energy: 10.0 },
    },
    PATPhotons_V1: {
      type: SHAPE,
      on: true,
      group: "Physics",
      name: "Photons (PAT)",
      fn: makePhoton,
      style: { color: "rgb(67%, 0%, 100%)", opacity: 1.0, linewidth: 2 },
      selection: { min_energy: 10.0 },
    },
    GlobalMuons_V1: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Global Muons (Reco)",
      extra: "Points_V1",
      assoc: "MuonGlobalPoints_V1",
      fn: makeTrackPoints,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 1.0, linewidth: 3 },
      selection: { min_pt: 1.0, index: 0 },
    },
    GlobalMuons_V2: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Global Muons (Reco)",
      extra: "Points_V1",
      assoc: "MuonGlobalPoints_V1",
      fn: makeTrackPoints,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 1.0, linewidth: 3 },
      selection: { min_pt: 1.0, index: 0 },
    },
    PATGlobalMuons_V1: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Global Muons (PAT)",
      extra: "Points_V1",
      assoc: "PATMuonGlobalPoints_V1",
      fn: makeTrackPoints,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 1.0, linewidth: 3 },
      selection: { min_pt: 1.0, index: 0 },
    },
    StandaloneMuons_V1: {
      type: ASSOC,
      on: false,
      group: "Physics",
      name: "Stand-alone Muons (Reco)",
      extra: "Points_V1",
      assoc: "MuonStandalonePoints_V1",
      fn: makeTrackPoints,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 1.0, linewidth: 3 },
      selection: { min_pt: 1.0, index: 0 },
    },
    StandaloneMuons_V2: {
      type: ASSOC,
      on: false,
      group: "Physics",
      name: "Stand-alone Muons (Reco)",
      extra: "Extras_V1",
      assoc: "MuonTrackExtras_V1",
      fn: makeTracks,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 1.0, linewidth: 1 },
      selection: { min_pt: 1.0, index: 0 },
    },
    PATStandaloneMuons_V1: {
      type: ASSOC,
      on: false,
      group: "Physics",
      name: "Stand-alone Muons (PAT)",
      extra: "Extras_V1",
      assoc: "PATMuonTrackExtras_V1",
      fn: makeTracks,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 1.0, linewidth: 1 },
      selection: { min_pt: 1.0, index: 0 },
    },
    TrackerMuons_V1: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Tracker Muons (Reco)",
      extra: "Points_V1",
      assoc: "MuonTrackerPoints_V1",
      fn: makeTrackPoints,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 1.0, linewidth: 1 },
      selection: { min_pt: 1.0, index: 0 },
    },
    TrackerMuons_V2: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Tracker Muons (Reco)",
      extra: "Extras_V1",
      assoc: "MuonTrackerExtras_V1",
      fn: makeTracks,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 1.0, linewidth: 1 },
      selection: { min_pt: 1.0, index: 0 },
    },
    PATTrackerMuons_V1: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Tracker Muons (PAT)",
      extra: "Points_V1",
      assoc: "PATMuonTrackerPoints_V1",
      fn: makeTrackPoints,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 1.0, linewidth: 1 },
      selection: { min_pt: 1.0, index: 0 },
    },
    PATTrackerMuons_V2: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Tracker Muons (PAT)",
      extra: "Extras_V1",
      assoc: "PATMuonTrackExtras_V1",
      fn: makeTracks,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 1.0, linewidth: 1 },
      selection: { min_pt: 1.0, index: 0 },
    },
    GsfElectrons_V1: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Electron Tracks (GSF)",
      extra: "Extras_V1",
      assoc: "GsfElectronExtras_V1",
      fn: makeThickTracks,
      style: { color: "rgb(10%, 100%, 10%)", opacity: 0.9, linewidth: 3 },
      selection: { min_pt: 1.0, index: 0 },
    },
    GsfElectrons_V2: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Electron Tracks (GSF)",
      extra: "Extras_V1",
      assoc: "GsfElectronExtras_V1",
      fn: makeThickTracks,
      style: { color: "rgb(10%, 100%, 10%)", opacity: 1, linewidth: 3 },
      selection: { min_pt: 1.0, index: 0 },
    },
    GsfElectrons_V3: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Electron Tracks (GSF)",
      extra: "Extras_V1",
      assoc: "GsfElectronExtras_V1",
      fn: makeThickTracks,
      style: { color: "rgb(10%, 100%, 10%)", opacity: 1, linewidth: 3 },
      selection: { min_pt: 1.0, index: 0 },
    },
    PATElectrons_V1: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Electron Tracks (PAT)",
      extra: "Extras_V1",
      assoc: "PATElectronExtras_V1",
      fn: makeThickTracks,
      style: { color: "rgb(10%, 100%, 10%)", opacity: 0.9, linewidth: 3 },
      selection: { min_pt: 1.0, index: 0 },
    },
    ForwardProtons_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "Forward Protons",
      fn: makeProtons,
      style: { color: "rgb(0%, 100%, 100%)", opacity: 1.0 },
      selection: {},
    },
    Vertices_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "Vertices (Reco)",
      fn: makeVertex,
      style: { radius: 0.001, color: "rgb(100%, 100%, 0%)", opacity: 0.9 },
    },
    PrimaryVertices_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "Primary Vertices (Reco)",
      fn: makeVertex,
      style: { radius: 0.001, color: "rgb(100%, 100%, 0%)", opacity: 0.9 },
    },
    SecondaryVertices_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "Secondary Vertices (Reco)",
      fn: makeVertex,
      style: { radius: 0.001, color: "rgb(100%, 40%, 0%)", opacity: 0.9 },
    },
    VertexCompositeCandidates_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "V0Vertices (Reco)",
      fn: makeVertexCompositeCandidate,
      style: { radius: 0.002, color: "rgb(100%, 0%, 0%)", opacity: 0.9 },
    },
    SimVertices_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "Vertices (Sim)",
      fn: makeSimVertex,
      style: { color: "rgb(80%, 20%, 0%)", opacity: 0.9 },
    },
  },

  RPhi: {
    SuperClusters_V1: {
      type: ASSOC,
      on: false,
      group: "ECAL",
      name: "SuperClusters",
      extra: "RecHitFractions_V1",
      assoc: "SuperClusterRecHitFractions_V1",
      fn: makeCaloClusters,
      style: { color: "rgb(100%, 20%, 0%)", opacity: 1.0 },
    },
    EBDigis_V1: {
      type: SCALEDSOLIDTOWER,
      on: false,
      group: "ECAL",
      name: "Barrel Digis",
      fn: makeEcalDigi,
      style: { color: "rgb(100%, 20%, 0%)", opacity: 0.5, linewidth: 0.5 },
      scale: 1.0,
      selection: { min_energy: 0.25 },
    },
    EBRecHits_V2: {
      type: SCALEDSOLIDTOWER,
      on: true,
      group: "ECAL",
      name: "Barrel Rec. Hits",
      fn: makeERecHit_V2,
      style: { color: "rgb(10%, 100%, 10%)", opacity: 0.5, linewidth: 0.5 },
      scale: 0.1,
      selection: { min_energy: 0.25 },
    },
    HGCEERecHits_V1: {
      type: SCALEDSOLIDBOX,
      on: true,
      group: "ECAL",
      name: "HGC EE Rec. Hits",
      fn: makeHGCRecHit,
      style: { color: "rgb(10%, 100%, 10%)", opacity: 0.5, linewidth: 0.25 },
      selection: { min_energy: 0.01 },
    },
    HFRecHits_V2: {
      type: SCALEDSOLIDBOX,
      on: false,
      group: "HCAL",
      name: "Forward Rec. Hits",
      fn: makeHRecHit_V2,
      style: { color: "rgb(60%, 100%, 100%)", opacity: 0.5, linewidth: 0.25 },
      selection: { min_energy: 0.0 },
    },
    HORecHits_V2: {
      type: SCALEDSOLIDBOX,
      on: false,
      group: "HCAL",
      name: "Outer Rec. Hits",
      fn: makeHRecHit_V2,
      style: { color: "rgb(20%, 70%, 100%)", opacity: 0.5, linewidth: 0.25 },
      selection: { min_energy: 1.0 },
    },
    HBRecHits_V2: {
      type: SCALEDSOLIDBOX,
      on: true,
      group: "HCAL",
      name: "Barrel Rec. Hits",
      fn: makeHRecHit_V2,
      style: { color: "rgb(20%, 70%, 100%)", opacity: 0.5, linewidth: 0.25 },
      selection: { min_energy: 0.0 },
    },
    HGCHEBRecHits_V1: {
      type: SCALEDSOLIDBOX,
      on: true,
      group: "HCAL",
      name: "HGC HE Back Rec. Hits",
      fn: makeHGCRecHit,
      style: { color: "rgb(20%, 70%, 100%)", opacity: 0.5, linewidth: 0.25 },
      selection: { min_energy: 0.01 },
    },
    HGCHEFRecHits_V1: {
      type: SCALEDSOLIDBOX,
      on: true,
      group: "HCAL",
      name: "HGC HE Front Rec. Hits",
      fn: makeHGCRecHit,
      style: { color: "rgb(20%, 70%, 100%)", opacity: 0.5, linewidth: 0.25 },
      selection: { min_energy: 0.01 },
    },
    Tracks_V1: {
      type: ASSOC,
      on: true,
      group: "Tracking",
      name: "Tracks (reco.)",
      extra: "Extras_V1",
      assoc: "TrackExtras_V1",
      fn: makeTracks,
      style: {
        color: "rgb(100%, 100%, 0%)",
        opacity: 0.5,
        lineCaps: "square",
        linewidth: 1,
      },
      selection: { min_pt: 1.0, index: 2 },
    },
    Tracks_V2: {
      type: ASSOC,
      on: true,
      group: "Tracking",
      name: "Tracks (reco.)",
      extra: "Extras_V1",
      assoc: "TrackExtras_V1",
      fn: makeTracks,
      style: {
        color: "rgb(100%, 100%, 0%)",
        opacity: 0.5,
        lineCaps: "square",
        linewidth: 1,
      },
      selection: { min_pt: 1.0, index: 2 },
    },
    Tracks_V3: {
      type: ASSOC,
      on: true,
      group: "Tracking",
      name: "Tracks (reco.)",
      extra: "Extras_V1",
      assoc: "TrackExtras_V1",
      fn: makeTracks,
      style: {
        color: "rgb(100%, 100%, 0%)",
        opacity: 0.5,
        lineCaps: "square",
        linewidth: 1,
      },
      selection: { min_pt: 1.0, index: 2 },
    },
    Tracks_V4: {
      type: ASSOC,
      on: true,
      group: "Tracking",
      name: "Tracks (reco.)",
      extra: "Extras_V1",
      assoc: "TrackExtras_V1",
      fn: makeTracks,
      style: {
        color: "rgb(100%, 100%, 0%)",
        opacity: 0.5,
        lineCaps: "square",
        linewidth: 1,
      },
      selection: { min_pt: 1.0, index: 2 },
    },
    TrackDets_V1: {
      type: BOX,
      on: false,
      group: "Tracking",
      name: "Matching Tracker Dets",
      fn: makeTrackerPiece,
      style: { color: "rgb(100%, 100%, 0%)", opacity: 0.5, linewidth: 0.5 },
    },
    TrackingRecHits_V1: {
      type: POINT,
      on: false,
      group: "Tracking",
      name: "Tracking Rec Hits",
      fn: makeTrackingRecHits,
      style: { color: "rgb(100%, 100%, 0%)", size: 2 },
    },
    SiStripClusters_V1: {
      type: POINT,
      on: false,
      group: "Tracking",
      name: "Si Strip Clusters",
      fn: makeTrackingClusters,
      style: { color: "rgb(80%, 20%, 0%)", size: 2 },
    },
    SiPixelClusters_V1: {
      type: POINT,
      on: false,
      group: "Tracking",
      name: "Si Pixel Clusters",
      fn: makeTrackingClusters,
      style: { color: "rgb(100%, 40%, 0%)", size: 2 },
    },
    Event_V1: {
      type: TEXT,
      on: true,
      group: "Provenance",
      name: "Event",
      fn: makeEvent,
      style: {},
    },
    Event_V2: {
      type: TEXT,
      on: true,
      group: "Provenance",
      name: "Event",
      fn: makeEvent,
      style: {},
    },
    Event_V3: {
      type: TEXT,
      on: true,
      group: "Provenance",
      name: "Event",
      fn: makeEvent,
      style: {},
    },
    DTRecHits_V1: {
      type: SOLIDBOX,
      on: false,
      group: "Muon",
      name: "DT Rec. Hits",
      fn: makeDTRecHits,
      style: { color: "rgb(0%, 100%, 0%)", opacity: 0.5, linewidth: 1 },
    },
    DTRecSegment4D_V1: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "DT Rec. Segments (4D)",
      fn: makeDTRecSegments,
      style: { color: "rgb(100%, 100%, 0%)", opacity: 1.0, linewidth: 1.5 },
    },
    RPCRecHits_V1: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "RPC Rec. Hits",
      fn: makeRPCRecHits,
      style: { color: "rgb(80%, 100%, 0%)", opacity: 1.0, linewidth: 1.5 },
    },
    MatchingGEMs_V1: {
      type: SOLIDBOX,
      on: true,
      group: "Muon",
      name: "Matching GEMs",
      fn: makeMuonChamber,
      style: { color: "rgb(100%,0%,10%)", opacity: 0.1, linewidth: 1 },
    },
    GEMDigis_V2: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "GEM Strip Digis",
      fn: makeGEMDigis_V2,
      style: { color: "rgb(100%, 10%, 100%)", opacity: 0.8, linewidth: 1 },
    },
    GEMRecHits_V2: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "GEM Rec. Hits (2D)",
      fn: makeGEMRecHits_V2,
      style: { color: "rgb(60%, 100%, 70%)", opacity: 1.0, linewidth: 1 },
    },
    GEMSegments_V1: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "GEM Segments",
      fn: makeGEMSegments_V2,
      style: { color: "rgb(100%, 70%, 100%)", opacity: 1.0, linewidth: 1 },
    },
    GEMSegments_V2: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "GEM Segments",
      fn: makeGEMSegments_V2,
      style: { color: "rgb(100%, 70%, 100%)", opacity: 1.0, linewidth: 1 },
    },
    GEMSegments_V3: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "GEM Segments",
      fn: makeGEMSegments_V2,
      style: { color: "rgb(100%, 70%, 100%)", opacity: 1.0, linewidth: 1 },
    },
    CSCStripDigis_V1: {
      type: SOLIDBOX,
      on: false,
      group: "Muon",
      name: "CSC Strip Digis",
      fn: makeCSCStripDigis,
      style: { color: "rgb(100%, 20%, 100%)", opacity: 0.5, linewidth: 1 },
    },
    CSCWireDigis_V1: {
      type: SOLIDBOX,
      on: false,
      group: "Muon",
      name: "CSC Wire Digis",
      fn: makeCSCWireDigis,
      style: { color: "rgb(100%, 60%, 100%)", opacity: 0.5, linewidth: 1 },
    },
    CSCStripDigis_V2: {
      type: LINE,
      on: false,
      group: "Muon",
      name: "CSC Strip Digis",
      fn: makeCSCDigis_V2,
      style: { color: "rgb(100%, 20%, 100%)", opacity: 0.8, linewidth: 1 },
    },
    CSCWireDigis_V2: {
      type: LINE,
      on: false,
      group: "Muon",
      name: "CSC Wire Digis",
      fn: makeCSCDigis_V2,
      style: { color: "rgb(100%, 60%, 100%)", opacity: 0.5, linewidth: 1 },
    },
    CSCLCTDigis_V1: {
      type: POINT,
      on: false,
      group: "Muon",
      name: "CSC LCT Digis",
      fn: makeCSCLCTDigis,
      style: { color: "rgb(0%, 100%, 100%)", size: 0.15 },
    },
    CSCCorrelatedLCTDigis_V2: {
      type: LINE,
      on: false,
      group: "Muon",
      name: "CSC Correlated LCT Digis",
      fn: makeCSCLCTCorrelatedLCTDigis,
      style: { color: "rgb(0%,100%,100%)", opacity: 0.8, linewidth: 2 },
    },
    MatchingCSCs_V1: {
      type: SOLIDBOX,
      on: true,
      group: "Muon",
      name: "Matching CSCs",
      fn: makeMuonChamber,
      style: { color: "rgb(100%,0%,0%)", opacity: 0.1, linewidth: 1 },
    },
    CSCRecHit2Ds_V2: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "CSC Rec. Hits (2D)",
      fn: makeCSCRecHit2Ds_V2,
      style: { color: "rgb(60%, 100%, 90%)", opacity: 1.0, linewidth: 1 },
    },
    CSCSegments_V1: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "CSC Segments",
      fn: makeCSCSegments,
      style: { color: "rgb(100%, 60%, 100%)", opacity: 1.0, linewidth: 1.5 },
    },
    CSCSegments_V2: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "CSC Segments",
      fn: makeCSCSegments,
      style: { color: "rgb(100%, 60%, 100%)", opacity: 1.0, linewidth: 1.5 },
    },
    CSCSegments_V3: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "CSC Segments",
      fn: makeCSCSegments,
      style: { color: "rgb(100%, 60%, 100%)", opacity: 1.0, linewidth: 1.5 },
    },
    MuonChambers_V1: {
      type: SOLIDBOX,
      on: true,
      group: "Muon",
      name: "Matching muon chambers",
      fn: makeMuonChamber,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 0.1, linewidth: 1 },
    },
    CaloTowers_V2: {
      type: STACKEDTOWER,
      on: false,
      group: "Physics",
      name: "Calo Towers",
      fn: makeCaloTower,
      style: {
        ecolor: "rgb(100%, 0%, 0%)",
        hcolor: "rgb(0%, 0%, 100%)",
        opacity: 0.5,
        linewidth: 1.0,
      },
      scale: 0.1,
      selection: { min_energy: 0.1 },
    },
    CaloTowers_V3: {
      type: STACKEDTOWER,
      on: false,
      group: "Physics",
      name: "Calo Towers",
      fn: makeCaloTower,
      style: {
        ecolor: "rgb(100%, 0%, 0%)",
        hcolor: "rgb(0%, 0%, 100%)",
        opacity: 0.5,
        linewidth: 1.0,
      },
      scale: 0.1,
      selection: { min_energy: 1.0 },
    },
    METs_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "Missing Et (Reco)",
      fn: makeMET,
      style: { color: "rgb(100%, 50%, 100%)", linewidth: 2, scale: 0.025 },
      selection: { min_pt: 0.0 },
    },
    PFMETs_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "Missing Et (PF)",
      fn: makeMET,
      style: { color: "rgb(100%, 50%, 100%)", linewidth: 2, scale: 0.025 },
      selection: { min_pt: 0.0 },
    },
    PATMETs_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "Missing Et (PAT)",
      fn: makeMET,
      style: { color: "rgb(100%, 50%, 100%)", linewidth: 2, scale: 0.025 },
      selection: { min_pt: 0.0 },
    },
    Jets_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "Jets (Reco)",
      fn: makeJet,
      style: { color: "rgb(100%, 100%, 0%)", opacity: 0.75 },
      selection: { min_et: 10.0 },
    },
    PFJets_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "Jets (PF)",
      fn: makeJet,
      style: { color: "rgb(100%, 100%, 0%)", opacity: 0.6 },
      selection: { min_et: 10.0 },
      cuts: true,
    },
    PFJets_V2: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "Jets (PF)",
      fn: makeJetWithVertex,
      style: { color: "rgb(100%, 100%, 0%)", opacity: 0.6 },
      selection: { min_et: 10.0 },
      cuts: true,
    },
    GenJets_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "Jets (Sim)",
      fn: makeJet,
      style: { color: "rgb(100%, 75%, 0%)", opacity: 0.8 },
      selection: { min_et: 10.0 },
    },
    PATJets_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "Jets (PAT)",
      fn: makeJet,
      style: { color: "rgb(100%, 50%, 0%)", opacity: 0.3 },
      selection: { min_et: 10.0 },
    },
    Photons_V1: {
      type: SHAPE,
      on: true,
      group: "Physics",
      name: "Photons (Reco)",
      fn: makePhoton,
      style: { color: "rgb(67%, 0%, 100%)", opacity: 1.0, linewidth: 2 },
      selection: { min_energy: 10.0 },
    },
    PATPhotons_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "Photons (PAT)",
      fn: makePhoton,
      style: { color: "rgb(67%, 0%, 100%)", opacity: 1.0, linewidth: 2 },
      selection: { min_energy: 10.0 },
    },
    GlobalMuons_V1: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Global Muons (Reco)",
      extra: "Points_V1",
      assoc: "MuonGlobalPoints_V1",
      fn: makeTrackPoints,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 1.0, linewidth: 3 },
      selection: { min_pt: 1.0, index: 0 },
    },
    GlobalMuons_V2: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Global Muons (Reco)",
      extra: "Points_V1",
      assoc: "MuonGlobalPoints_V1",
      fn: makeTrackPoints,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 1.0, linewidth: 3 },
      selection: { min_pt: 1.0, index: 0 },
    },
    PATGlobalMuons_V1: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Global Muons (PAT)",
      extra: "Points_V1",
      assoc: "PATMuonGlobalPoints_V1",
      fn: makeTrackPoints,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 1.0, linewidth: 3 },
      selection: { min_pt: 1.0, index: 0 },
    },
    StandaloneMuons_V1: {
      type: ASSOC,
      on: false,
      group: "Physics",
      name: "Stand-alone Muons (Reco)",
      extra: "Points_V1",
      assoc: "MuonStandalonePoints_V1",
      fn: makeTrackPoints,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 1.0, linewidth: 3 },
      selection: { min_pt: 1.0, index: 0 },
    },
    StandaloneMuons_V2: {
      type: ASSOC,
      on: false,
      group: "Physics",
      name: "Stand-alone Muons (Reco)",
      extra: "Extras_V1",
      assoc: "MuonTrackExtras_V1",
      fn: makeTracks,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 1.0, linewidth: 1 },
      selection: { min_pt: 1.0, index: 0 },
    },
    PATStandaloneMuons_V1: {
      type: ASSOC,
      on: false,
      group: "Physics",
      name: "Stand-alone Muons (PAT)",
      extra: "Extras_V1",
      assoc: "PATMuonTrackExtras_V1",
      fn: makeTracks,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 1.0, linewidth: 1 },
      selection: { min_pt: 1.0, index: 0 },
    },
    TrackerMuons_V1: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Tracker Muons (Reco)",
      extra: "Points_V1",
      assoc: "MuonTrackerPoints_V1",
      fn: makeTrackPoints,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 1.0, linewidth: 1 },
      selection: { min_pt: 1.0, index: 0 },
    },
    TrackerMuons_V2: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Tracker Muons (Reco)",
      extra: "Extras_V1",
      assoc: "MuonTrackerExtras_V1",
      fn: makeTracks,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 1.0, linewidth: 1 },
      selection: { min_pt: 1.0, index: 0 },
    },
    PATTrackerMuons_V1: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Tracker Muons (PAT)",
      extra: "Points_V1",
      assoc: "PATMuonTrackerPoints_V1",
      fn: makeTrackPoints,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 1.0, linewidth: 1 },
      selection: { min_pt: 1.0, index: 0 },
    },
    PATTrackerMuons_V2: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Tracker Muons (PAT)",
      extra: "Extras_V1",
      assoc: "PATMuonTrackExtras_V1",
      fn: makeTracks,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 1.0, linewidth: 1 },
      selection: { min_pt: 1.0, index: 0 },
    },
    GsfElectrons_V1: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Electron Tracks (GSF)",
      extra: "Extras_V1",
      assoc: "GsfElectronExtras_V1",
      fn: makeThickTracks,
      style: { color: "rgb(10%, 100%, 10%)", opacity: 0.9, linewidth: 3 },
      selection: { min_pt: 1.0, index: 0 },
    },
    GsfElectrons_V2: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Electron Tracks (GSF)",
      extra: "Extras_V1",
      assoc: "GsfElectronExtras_V1",
      fn: makeThickTracks,
      style: { color: "rgb(10%, 100%, 10%)", opacity: 1, linewidth: 3 },
      selection: { min_pt: 1.0, index: 0 },
    },
    GsfElectrons_V3: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Electron Tracks (GSF)",
      extra: "Extras_V1",
      assoc: "GsfElectronExtras_V1",
      fn: makeThickTracks,
      style: { color: "rgb(10%, 100%, 10%)", opacity: 1, linewidth: 3 },
      selection: { min_pt: 1.0, index: 0 },
    },
    PATElectrons_V1: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Electron Tracks (PAT)",
      extra: "Extras_V1",
      assoc: "PATElectronExtras_V1",
      fn: makeThickTracks,
      style: { color: "rgb(10%, 100%, 10%)", opacity: 0.9, linewidth: 3 },
      selection: { min_pt: 1.0, index: 0 },
    },
    Vertices_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "Vertices (Reco)",
      fn: makeVertex,
      style: { radius: 0.001, color: "rgb(100%, 100%, 0%)", opacity: 0.9 },
    },
    PrimaryVertices_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "Primary Vertices (Reco)",
      fn: makeVertex,
      style: { radius: 0.01, color: "rgb(100%, 100%, 0%)", opacity: 0.9 },
    },
    SecondaryVertices_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "Secondary Vertices (Reco)",
      fn: makeVertex,
      style: { radius: 0.01, color: "rgb(100%, 40%, 0%)", opacity: 0.9 },
    },
    VertexCompositeCandidates_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "V0Vertices (Reco)",
      fn: makeVertexCompositeCandidate,
      style: { radius: 0.02, color: "rgb(100%, 0%, 0%)", opacity: 0.9 },
    },
    SimVertices_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "Vertices (Sim)",
      fn: makeSimVertex,
      style: { color: "rgb(80%, 20%, 0%)", opacity: 0.9 },
    },
  },

  RhoZ: {
    EEDigis_V1: {
      type: SCALEDSOLIDTOWER,
      on: false,
      group: "ECAL",
      name: "Endcap Digis",
      fn: makeEcalDigi,
      style: { color: "rgb(100%, 20%, 0%)", opacity: 0.5, linewidth: 0.5 },
      scale: 1.0,
      selection: { min_energy: 0.5 },
    },
    EBDigis_V1: {
      type: SCALEDSOLIDTOWER,
      on: false,
      group: "ECAL",
      name: "Barrel Digis",
      fn: makeEcalDigi,
      style: { color: "rgb(100%, 20%, 0%)", opacity: 0.5, linewidth: 0.5 },
      scale: 1.0,
      selection: { min_energy: 0.25 },
    },
    EERecHits_V2: {
      type: SCALEDSOLIDTOWER,
      on: true,
      group: "ECAL",
      name: "Endcap Rec. Hits",
      fn: makeERecHit_RZ,
      style: { color: "rgb(10%, 100%, 10%)", opacity: 0.5, linewidth: 0.5 },
      scale: 0.01,
      selection: { min_energy: 0.5 },
    },
    ESRecHits_V2: {
      type: SCALEDSOLIDTOWER,
      on: false,
      group: "ECAL",
      name: "Preshower Rec. Hits",
      fn: makeERecHit_RZ,
      style: { color: "rgb(100%, 60%, 0%)", opacity: 0.5, linewidth: 0.5 },
      scale: 100.0,
      selection: { min_energy: 0.0005 },
    },
    EBRecHits_V2: {
      type: SCALEDSOLIDTOWER,
      on: true,
      group: "ECAL",
      name: "Barrel Rec. Hits",
      fn: makeERecHit_RZ,
      style: { color: "rgb(10%, 100%, 10%)", opacity: 0.5, linewidth: 0.5 },
      scale: 0.1,
      selection: { min_energy: 0.25 },
    },
    EcalTowers_V1: {
      type: SCALEDSOLIDTOWER,
      on: false,
      group: "ECAL",
      name: "EcalTowers",
      fn: makeEcalPFCandidateTowersRZ,
      style: { color: "rgb(10%, 100%, 10%)", opacity: 0.5, scale: 0.1 },
      selection: { min_energy: 1.5 },
    },
    HcalTowers_V1: {
      type: SCALEDSOLIDTOWER,
      on: false,
      group: "HCAL",
      name: "HcalTowers",
      fn: makeHcalPFCandidateTowersRZ,
      style: { color: "rgb(20%, 70%, 100%)", opacity: 0.5, scale: 0.1 },
      selection: { min_energy: 1.5 },
    },
    HGCEERecHits_V1: {
      type: SCALEDSOLIDBOX,
      on: true,
      group: "ECAL",
      name: "HGC EE Rec. Hits",
      fn: makeHGCRecHit,
      style: { color: "rgb(10%, 100%, 10%)", opacity: 0.5, linewidth: 0.25 },
      selection: { min_energy: 0.01 },
    },
    HFRecHits_V2: {
      type: SCALEDSOLIDBOX,
      on: true,
      group: "HCAL",
      name: "Forward Rec. Hits",
      fn: makeHRecHit_RZ,
      style: { color: "rgb(60%, 100%, 100%)", opacity: 0.5, linewidth: 0.25 },
      selection: { min_energy: 0.0 },
    },
    HORecHits_V2: {
      type: SCALEDSOLIDBOX,
      on: true,
      group: "HCAL",
      name: "Outer Rec. Hits",
      fn: makeHRecHit_RZ,
      style: { color: "rgb(20%, 70%, 100%)", opacity: 0.5, linewidth: 0.25 },
      selection: { min_energy: 1.0 },
    },
    HERecHits_V2: {
      type: SCALEDSOLIDBOX,
      on: true,
      group: "HCAL",
      name: "Endcap Rec. Hits",
      fn: makeHRecHit_RZ,
      style: { color: "rgb(20%, 70%, 100%)", opacity: 0.5, linewidth: 0.25 },
      selection: { min_energy: 0.0 },
    },
    HBRecHits_V2: {
      type: SCALEDSOLIDBOX,
      on: true,
      group: "HCAL",
      name: "Barrel Rec. Hits",
      fn: makeHRecHit_RZ,
      style: { color: "rgb(20%, 70%, 100%)", opacity: 0.5, linewidth: 0.25 },
      selection: { min_energy: 0.0 },
    },
    HGCHEBRecHits_V1: {
      type: SCALEDSOLIDBOX,
      on: true,
      group: "HCAL",
      name: "HGC HE Back Rec. Hits",
      fn: makeHGCRecHit,
      style: { color: "rgb(20%, 70%, 100%)", opacity: 0.5, linewidth: 0.25 },
      selection: { min_energy: 0.01 },
    },
    HGCHEFRecHits_V1: {
      type: SCALEDSOLIDBOX,
      on: true,
      group: "HCAL",
      name: "HGC HE Front Rec. Hits",
      fn: makeHGCRecHit,
      style: { color: "rgb(20%, 70%, 100%)", opacity: 0.5, linewidth: 0.25 },
      selection: { min_energy: 0.01 },
    },
    Tracks_V1: {
      type: ASSOC,
      on: true,
      group: "Tracking",
      name: "Tracks (reco.)",
      extra: "Extras_V1",
      assoc: "TrackExtras_V1",
      fn: makeTracksRZ,
      style: {
        color: "rgb(100%, 100%, 0%)",
        opacity: 0.5,
        lineCaps: "square",
        linewidth: 1,
      },
      selection: { min_pt: 1.0, index: 2 },
    },
    Tracks_V2: {
      type: ASSOC,
      on: true,
      group: "Tracking",
      name: "Tracks (reco.)",
      extra: "Extras_V1",
      assoc: "TrackExtras_V1",
      fn: makeTracksRZ,
      style: {
        color: "rgb(100%, 100%, 0%)",
        opacity: 0.5,
        lineCaps: "square",
        linewidth: 1,
      },
      selection: { min_pt: 1.0, index: 2 },
    },
    Tracks_V3: {
      type: ASSOC,
      on: true,
      group: "Tracking",
      name: "Tracks (reco.)",
      extra: "Extras_V1",
      assoc: "TrackExtras_V1",
      fn: makeTracksRZ,
      style: {
        color: "rgb(100%, 100%, 0%)",
        opacity: 0.5,
        lineCaps: "square",
        linewidth: 1,
      },
      selection: { min_pt: 1.0, index: 2 },
    },
    Tracks_V4: {
      type: ASSOC,
      on: true,
      group: "Tracking",
      name: "Tracks (reco.)",
      extra: "Extras_V1",
      assoc: "TrackExtras_V1",
      fn: makeTracksRZ,
      style: {
        color: "rgb(100%, 100%, 0%)",
        opacity: 0.5,
        lineCaps: "square",
        linewidth: 1,
      },
      selection: { min_pt: 1.0, index: 2 },
    },
    TrackDets_V1: {
      type: BOX,
      on: false,
      group: "Tracking",
      name: "Matching Tracker Dets",
      fn: makeTrackerPiece,
      style: { color: "rgb(100%, 100%, 0%)", opacity: 0.5, linewidth: 0.5 },
    },
    TrackingRecHits_V1: {
      type: POINT,
      on: false,
      group: "Tracking",
      name: "Tracking Rec Hits",
      fn: makeTrackingRecHitsRZ,
      style: { color: "rgb(100%, 100%, 0%)", size: 2 },
    },
    SiStripClusters_V1: {
      type: POINT,
      on: false,
      group: "Tracking",
      name: "Si Strip Clusters",
      fn: makeTrackingClustersRZ,
      style: { color: "rgb(80%, 20%, 0%)", size: 2 },
    },
    SiPixelClusters_V1: {
      type: POINT,
      on: false,
      group: "Tracking",
      name: "Si Pixel Clusters",
      fn: makeTrackingClustersRZ,
      style: { color: "rgb(100%, 40%, 0%)", size: 2 },
    },
    Event_V1: {
      type: TEXT,
      on: true,
      group: "Provenance",
      name: "Event",
      fn: makeEvent,
      style: {},
    },
    Event_V2: {
      type: TEXT,
      on: true,
      group: "Provenance",
      name: "Event",
      fn: makeEvent,
      style: {},
    },
    Event_V3: {
      type: TEXT,
      on: true,
      group: "Provenance",
      name: "Event",
      fn: makeEvent,
      style: {},
    },
    DTRecHits_V1: {
      type: SOLIDBOX,
      on: false,
      group: "Muon",
      name: "DT Rec. Hits",
      fn: makeDTRecHitsRZ,
      style: { color: "rgb(0%, 100%, 0%)", opacity: 0.5, linewidth: 1 },
    },
    DTRecSegment4D_V1: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "DT Rec. Segments (4D)",
      fn: makeDTRecSegmentsRZ,
      style: { color: "rgb(100%, 100%, 0%)", opacity: 1.0, linewidth: 1.5 },
    },
    RPCRecHits_V1: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "RPC Rec. Hits",
      fn: makeRPCRecHitsRZ,
      style: { color: "rgb(80%, 100%, 0%)", opacity: 1.0, linewidth: 1.5 },
    },
    MatchingGEMs_V1: {
      type: SOLIDBOX,
      on: true,
      group: "Muon",
      name: "Matching GEMs",
      fn: makeMuonChamber,
      style: { color: "rgb(100%,0%,10%)", opacity: 0.1, linewidth: 1 },
    },
    GEMDigis_V2: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "GEM Strip Digis",
      fn: makeGEMDigis_V2,
      style: { color: "rgb(100%, 10%, 100%)", opacity: 0.8, linewidth: 1 },
    },
    GEMRecHits_V2: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "GEM Rec. Hits (2D)",
      fn: makeGEMRecHitsRZ,
      style: { color: "rgb(60%, 100%, 70%)", opacity: 1.0, linewidth: 1 },
    },
    GEMSegments_V1: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "GEM Segments",
      fn: makeGEMSegments_V2,
      style: { color: "rgb(100%, 70%, 100%)", opacity: 1.0, linewidth: 1 },
    },
    GEMSegments_V2: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "GEM Segments",
      fn: makeGEMSegments_V2,
      style: { color: "rgb(100%, 70%, 100%)", opacity: 1.0, linewidth: 1 },
    },
    GEMSegments_V3: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "GEM Segments",
      fn: makeGEMSegments_V2,
      style: { color: "rgb(100%, 70%, 100%)", opacity: 1.0, linewidth: 1 },
    },
    CSCStripDigis_V1: {
      type: SOLIDBOX,
      on: false,
      group: "Muon",
      name: "CSC Strip Digis",
      fn: makeCSCStripDigis,
      style: { color: "rgb(100%, 20%, 100%)", opacity: 0.5, linewidth: 1 },
    },
    CSCWireDigis_V1: {
      type: SOLIDBOX,
      on: false,
      group: "Muon",
      name: "CSC Wire Digis",
      fn: makeCSCWireDigis,
      style: { color: "rgb(100%, 60%, 100%)", opacity: 0.5, linewidth: 1 },
    },
    CSCStripDigis_V2: {
      type: LINE,
      on: false,
      group: "Muon",
      name: "CSC Strip Digis",
      fn: makeCSCDigis_V2,
      style: { color: "rgb(100%, 20%, 100%)", opacity: 0.8, linewidth: 1 },
    },
    CSCWireDigis_V2: {
      type: LINE,
      on: false,
      group: "Muon",
      name: "CSC Wire Digis",
      fn: makeCSCDigis_V2,
      style: { color: "rgb(100%, 60%, 100%)", opacity: 0.5, linewidth: 1 },
    },
    CSCLCTDigis_V1: {
      type: POINT,
      on: false,
      group: "Muon",
      name: "CSC LCT Digis",
      fn: makeCSCLCTDigis,
      style: { color: "rgb(0%, 100%, 100%)", size: 0.15 },
    },
    CSCCorrelatedLCTDigis_V2: {
      type: LINE,
      on: false,
      group: "Muon",
      name: "CSC Correlated LCT Digis",
      fn: makeCSCLCTCorrelatedLCTDigis,
      style: { color: "rgb(0%,100%,100%)", opacity: 0.8, linewidth: 2 },
    },
    CSCRecHit2Ds_V2: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "CSC Rec. Hits (2D)",
      fn: makeCSCRecHit2DsRZ,
      style: { color: "rgb(60%, 100%, 90%)", opacity: 1.0, linewidth: 1 },
    },
    CSCSegments_V1: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "CSC Segments",
      fn: makeCSCSegmentsRZ,
      style: { color: "rgb(100%, 60%, 100%)", opacity: 1.0, linewidth: 1.5 },
    },
    CSCSegments_V2: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "CSC Segments",
      fn: makeCSCSegmentsRZ,
      style: { color: "rgb(100%, 60%, 100%)", opacity: 1.0, linewidth: 1.5 },
    },
    CSCSegments_V3: {
      type: LINE,
      on: true,
      group: "Muon",
      name: "CSC Segments",
      fn: makeCSCSegmentsRZ,
      style: { color: "rgb(100%, 60%, 100%)", opacity: 1.0, linewidth: 1.5 },
    },
    CaloTowers_V2: {
      type: STACKEDTOWER,
      on: false,
      group: "Physics",
      name: "Calo Towers",
      fn: makeCaloTower,
      style: {
        ecolor: "rgb(100%, 0%, 0%)",
        hcolor: "rgb(0%, 0%, 100%)",
        opacity: 0.5,
        linewidth: 1.0,
      },
      scale: 0.1,
      selection: { min_energy: 0.1 },
    },
    CaloTowers_V3: {
      type: STACKEDTOWER,
      on: false,
      group: "Physics",
      name: "Calo Towers",
      fn: makeCaloTower,
      style: {
        ecolor: "rgb(100%, 0%, 0%)",
        hcolor: "rgb(0%, 0%, 100%)",
        opacity: 0.5,
        linewidth: 1.0,
      },
      scale: 0.1,
      selection: { min_energy: 1.0 },
    },
    METs_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "Missing Et (Reco)",
      fn: makeMET,
      style: { color: "rgb(100%, 50%, 100%)", linewidth: 2, scale: 0.025 },
      selection: { min_pt: 0.0 },
    },
    PFMETs_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "Missing Et (PF)",
      fn: makeMET,
      style: { color: "rgb(100%, 50%, 100%)", linewidth: 2, scale: 0.025 },
      selection: { min_pt: 0.0 },
    },
    PATMETs_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "Missing Et (PAT)",
      fn: makeMET,
      style: { color: "rgb(100%, 50%, 100%)", linewidth: 2, scale: 0.025 },
      selection: { min_pt: 0.0 },
    },
    Jets_V1: {
      type: SHAPE,
      on: true,
      group: "Physics",
      name: "Jets (Reco)",
      fn: makeJetRZ,
      style: { color: "rgb(100%, 100%, 0%)", opacity: 0.75 },
      selection: { min_et: 10.0 },
    },
    PFJets_V1: {
      type: SHAPE,
      on: true,
      group: "Physics",
      name: "Jets (PF)",
      fn: makeJetRZ,
      style: { color: "rgb(100%, 100%, 0%)", opacity: 0.6 },
      selection: { min_et: 10.0 },
      cuts: true,
    },
    PFJets_V2: {
      type: SHAPE,
      on: true,
      group: "Physics",
      name: "Jets (PF)",
      fn: makeJetWithVertexRZ,
      style: { color: "rgb(100%, 100%, 0%)", opacity: 0.6 },
      selection: { min_et: 10.0 },
      cuts: true,
    },
    GenJets_V1: {
      type: SHAPE,
      on: true,
      group: "Physics",
      name: "Jets (Sim)",
      fn: makeJetRZ,
      style: { color: "rgb(100%, 75%, 0%)", opacity: 0.8 },
      selection: { min_et: 10.0 },
    },
    PATJets_V1: {
      type: SHAPE,
      on: true,
      group: "Physics",
      name: "Jets (PAT)",
      fn: makeJetRZ,
      style: { color: "rgb(100%, 50%, 0%)", opacity: 0.3 },
      selection: { min_et: 10.0 },
    },
    Photons_V1: {
      type: SHAPE,
      on: true,
      group: "Physics",
      name: "Photons (Reco)",
      fn: makePhotonRZ,
      style: { color: "rgb(67%, 0%, 100%)", opacity: 1.0, linewidth: 2 },
      selection: { min_energy: 10.0 },
    },
    PATPhotons_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "Photons (PAT)",
      fn: makePhotonRZ,
      style: { color: "rgb(67%, 0%, 100%)", opacity: 1.0, linewidth: 2 },
      selection: { min_energy: 10.0 },
    },
    GlobalMuons_V1: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Global Muons (Reco)",
      extra: "Points_V1",
      assoc: "MuonGlobalPoints_V1",
      fn: makeTrackPointsRZ,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 1.0, linewidth: 3 },
      selection: { min_pt: 1.0, index: 0 },
    },
    GlobalMuons_V2: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Global Muons (Reco)",
      extra: "Points_V1",
      assoc: "MuonGlobalPoints_V1",
      fn: makeTrackPointsRZ,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 1.0, linewidth: 3 },
      selection: { min_pt: 1.0, index: 0 },
    },
    PATGlobalMuons_V1: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Global Muons (PAT)",
      extra: "Points_V1",
      assoc: "PATMuonGlobalPoints_V1",
      fn: makeTrackPointsRZ,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 1.0, linewidth: 3 },
      selection: { min_pt: 1.0, index: 0 },
    },
    StandaloneMuons_V1: {
      type: ASSOC,
      on: false,
      group: "Physics",
      name: "Stand-alone Muons (Reco)",
      extra: "Points_V1",
      assoc: "MuonStandalonePoints_V1",
      fn: makeTrackPointsRZ,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 1.0, linewidth: 3 },
      selection: { min_pt: 1.0, index: 0 },
    },
    StandaloneMuons_V2: {
      type: ASSOC,
      on: false,
      group: "Physics",
      name: "Stand-alone Muons (Reco)",
      extra: "Extras_V1",
      assoc: "MuonTrackExtras_V1",
      fn: makeTracksRZ,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 1.0, linewidth: 1 },
      selection: { min_pt: 1.0, index: 0 },
    },
    PATStandaloneMuons_V1: {
      type: ASSOC,
      on: false,
      group: "Physics",
      name: "Stand-alone Muons (PAT)",
      extra: "Extras_V1",
      assoc: "PATMuonTrackExtras_V1",
      fn: makeTracksRZ,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 1.0, linewidth: 1 },
      selection: { min_pt: 1.0, index: 0 },
    },
    TrackerMuons_V1: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Tracker Muons (Reco)",
      extra: "Points_V1",
      assoc: "MuonTrackerPoints_V1",
      fn: makeTrackPointsRZ,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 1.0, linewidth: 1 },
      selection: { min_pt: 1.0, index: 0 },
    },
    TrackerMuons_V2: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Tracker Muons (Reco)",
      extra: "Extras_V1",
      assoc: "MuonTrackerExtras_V1",
      fn: makeTracksRZ,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 1.0, linewidth: 1 },
      selection: { min_pt: 1.0, index: 0 },
    },
    PATTrackerMuons_V1: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Tracker Muons (PAT)",
      extra: "Points_V1",
      assoc: "PATMuonTrackerPoints_V1",
      fn: makeTrackPointsRZ,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 1.0, linewidth: 1 },
      selection: { min_pt: 1.0, index: 0 },
    },
    PATTrackerMuons_V2: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Tracker Muons (PAT)",
      extra: "Extras_V1",
      assoc: "PATMuonTrackExtras_V1",
      fn: makeTracksRZ,
      style: { color: "rgb(100%, 0%, 0%)", opacity: 1.0, linewidth: 1 },
      selection: { min_pt: 1.0, index: 0 },
    },
    GsfElectrons_V1: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Electron Tracks (GSF)",
      extra: "Extras_V1",
      assoc: "GsfElectronExtras_V1",
      fn: makeThickTracksRZ,
      style: { color: "rgb(10%, 100%, 10%)", opacity: 0.9, linewidth: 3 },
      selection: { min_pt: 1.0, index: 0 },
    },
    GsfElectrons_V2: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Electron Tracks (GSF)",
      extra: "Extras_V1",
      assoc: "GsfElectronExtras_V1",
      fn: makeThickTracksRZ,
      style: { color: "rgb(10%, 100%, 10%)", opacity: 1, linewidth: 3 },
      selection: { min_pt: 1.0, index: 0 },
    },
    GsfElectrons_V3: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Electron Tracks (GSF)",
      extra: "Extras_V1",
      assoc: "GsfElectronExtras_V1",
      fn: makeThickTracksRZ,
      style: { color: "rgb(10%, 100%, 10%)", opacity: 1, linewidth: 3 },
      selection: { min_pt: 1.0, index: 0 },
    },
    PATElectrons_V1: {
      type: ASSOC,
      on: true,
      group: "Physics",
      name: "Electron Tracks (PAT)",
      extra: "Extras_V1",
      assoc: "PATElectronExtras_V1",
      fn: makeThickTracksRZ,
      style: { color: "rgb(10%, 100%, 10%)", opacity: 0.9, linewidth: 3 },
      selection: { min_pt: 1.0, index: 0 },
    },
    ForwardProtons_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "Forward Protons",
      fn: makeProtons,
      style: { color: "rgb(0%, 100%, 100%)", opacity: 1.0 },
      selection: {},
    },
    Vertices_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "Vertices (Reco)",
      fn: makeVertex,
      style: { radius: 0.001, color: "rgb(100%, 100%, 0%)", opacity: 0.9 },
    },
    PrimaryVertices_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "Primary Vertices (Reco)",
      fn: makeVertex,
      style: { radius: 0.01, color: "rgb(100%, 100%, 0%)", opacity: 0.9 },
    },
    SecondaryVertices_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "Secondary Vertices (Reco)",
      fn: makeVertex,
      style: { radius: 0.01, color: "rgb(100%, 40%, 0%)", opacity: 0.9 },
    },
    VertexCompositeCandidates_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "V0Vertices (Reco)",
      fn: makeVertexCompositeCandidate,
      style: { radius: 0.02, color: "rgb(100%, 0%, 0%)", opacity: 0.9 },
    },
    SimVertices_V1: {
      type: SHAPE,
      on: false,
      group: "Physics",
      name: "Vertices (Sim)",
      fn: makeSimVertex,
      style: { color: "rgb(80%, 20%, 0%)", opacity: 0.9 },
    },
  },
};

const disabled: Record<string, boolean> = {};

for (const view in detector_description) {
  if (!detector_description[view]) continue;
  for (const key in detector_description[view]) {
    if (!detector_description[view][key].on) {
      disabled[key] = true;
    }
  }
}

for (const view in event_description) {
  if (!event_description[view]) continue;
  for (const key in event_description[view]) {
    if (!event_description[view][key].on) {
      disabled[key] = true;
    }
  }
}

const data_groups = [
  "Provenance",
  "Tracking",
  "ECAL",
  "HCAL",
  "Muon",
  "Physics",
];

const reduced_data_groups = [
  { name: "Momentum Cut (GeV)", function: (group: string) => addControllers(group) },
  { name: "Show/Hide", function: (group: string) => addControllers(group) },
  { name: "Event Info", function: (group: string) => addInfo(group) },
];

export {
  detector_description,
  event_description,
  disabled,
  data_groups,
  reduced_data_groups,
};
